Repository auyer/Protonup-rs, pull requests merged in 2023-03, with the labels that each got.

#5 Fixes Quick Flatpak wrong path installation + updates iquire
  Cargo.lock
  README.md
  protonup-rs/Cargo.toml
  protonup-rs/src/main.rs
Labels: 🐛 Bug, 🤖 Dependabot

#8 fixes Labels in Enforce Label action
  .github/release-drafter.yml
  .github/workflows/enforce_label.yaml
Labels: ☁️ CI

#7 Fixed a couple things and would like to discuss a possible improvement
  README.md
  protonup-rs/src/main.rs
Labels: 💅 Improvement
